from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name="login"),
    path('employee/dashboard/', views.employee_dashboard, name="employee_dashboard"),
    path('manager/dashboard/', views.manager_dashboard, name="manager_dashboard"),
    path('manager/employees/', views.manage_employees, name="manage_employees"),
    path('manager/employees/add/', views.add_employee, name="add_employee"),
    path('manager/employees/edit/<int:user_id>/', views.edit_employee, name="edit_employee"),   # new
    path('manager/employees/delete/<int:user_id>/', views.delete_employee, name="delete_employee"),
    path("manage-projects/", views.manage_projects, name="manage_projects"),
    path("manage-projects/add/", views.add_project, name="add_project"),
    path("manage-projects/edit/<int:project_id>/", views.edit_project, name="edit_project"),
    path("manage-projects/delete/<int:project_id>/", views.delete_project, name="delete_project"),
    path("manage-resources/", views.manage_resources, name="manage_resources"),
    path("add_assigned_resource/", views.add_assigned_resource, name="add_assigned_resource"),
    path("resources/edit/<int:resource_id>/", views.edit_assigned_resource, name="edit_assigned_resource"),
    path("resources/delete/<int:resource_id>/", views.delete_assigned_resource, name="delete_assigned_resource"),
    path("manage-cw/", views.manage_cw, name="manage_cw"),
    path("manage_tasks/", views.manage_tasks, name="manage_tasks"),
    path("add_task/", views.add_task, name="add_task"),
    path('edit-task/<int:task_id>/', views.edit_task, name='edit_task'),
    path('delete-task/<int:task_id>/', views.delete_task, name='delete_task'),
    path('fill_monitoring/', views.fill_monitoring, name='fill_monitoring'),
    path('monitoring_success/', views.monitoring_success, name='monitoring_success'),
    path('monitoring-dashboard/', views.monitoring_dashboard, name='monitoring_dashboard'),
    path("consult_monitoring/", views.consult_monitoring, name="consult_monitoring"),
    path('export_monitoring/', views.export_monitoring_excel, name='export_monitoring_excel'),
    path('user/monitoring-dashboard/', views.user_monitoring_dashboard, name='user_monitoring_dashboard'),
    path('user/fill-monitoring/', views.user_fill_monitoring, name='user_fill_monitoring'),
    path('user/edit-profile/', views.user_edit_profile, name='user_edit_profile'),
    path('edit-monitoring/<int:entry_id>/', views.edit_monitoring, name='edit_monitoring'),
    path('delete-monitoring/<int:entry_id>/', views.delete_monitoring, name='delete_monitoring'),
    path("user/edit-monitoring/<int:entry_id>/", views.user_edit_monitoring, name="user_edit_monitoring"),
    path("user/delete-monitoring/<int:entry_id>/", views.user_delete_monitoring, name="user_delete_monitoring"),
    path('manager/edit-profile/', views.manager_edit_profile, name='manager_edit_profile'),
    path("consult-monitoring/cw/", views.consult_monitoring_cw, name="consult_monitoring_cw"),
    path("planned-dedications/", views.planned_dedication_list, name="planned_dedication_list"),
    # Placeholder for the future “Add” page
    path("planned-dedications/add/", views.add_planned_dedication, name="add_planned_dedication"), 
    path("planned/export/", views.export_monthly_dedication, name="export_monthly_dedication"),
    path('planned/edit/<int:pk>/', views.edit_planned_dedication, name='edit_planned_dedication'),
    path("planned/delete/<int:pk>/", views.delete_planned_dedication, name="delete_planned_dedication"),
    path("planned/export-overview/", views.export_overview_excel, name="export_overview_excel"),
    path("export-resources/", views.export_resources, name="export_resources"),
    path("export-projects/", views.export_projects_excel, name="export_projects_excel"),
    path('logout/', views.logout_view, name="logout"),
]
