# Generated by Django 5.2.5 on 2025-08-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
