# Generated by Django 5.2.5 on 2025-09-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cw', models.CharField(max_length=10)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_weeks', to='tracker.month')),
            ],
        ),
    ]
