# Generated by Django 5.2.5 on 2025-09-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_calendarweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarweek',
            name='cw',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='calendarweek',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_weeks', to='tracker.month'),
        ),
    ]
