# Generated by Django 5.2.5 on 2025-09-06 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='common_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracker.project'),
        ),
    ]
