# Generated by Django 5.2.5 on 2025-09-06 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_task_common_task_alter_task_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_spent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.calendarweek')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.month')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'task', 'cw')},
            },
        ),
    ]
