# Generated by Django 5.2.5 on 2025-09-06 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_monitoringentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.project'),
        ),
    ]
