# Generated by Django 5.2.5 on 2025-09-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_monitoringentry_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='special_user',
            field=models.BooleanField(default=False),
        ),
    ]
