# Generated by Django 5.2.5 on 2025-09-20 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_user_special_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_dedication', models.DecimalField(decimal_places=2, help_text='Planned dedication in hours or % (choose your unit).', max_digits=5)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_dedications', to='tracker.month')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_dedications', to='tracker.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_dedications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planned Dedication',
                'verbose_name_plural': 'Planned Dedications',
                'unique_together': {('user', 'project', 'month')},
            },
        ),
    ]
