# Generated by Django 5.2.5 on 2025-09-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_planneddedication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproject',
            name='dedication',
        ),
    ]
